# Generated by Django 5.1.1 on 2024-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('job_title', models.CharField(max_length=100, verbose_name='job_title')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('desc', models.CharField(max_length=500, verbose_name='desc')),
                ('skill_1', models.CharField(max_length=50, verbose_name='skill_1')),
                ('skill_2', models.CharField(max_length=50, verbose_name='skill_2')),
                ('skill_3', models.CharField(max_length=50, verbose_name='skill_3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
