# Generated by Django 5.1.1 on 2024-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='link',
            field=models.URLField(default=0, verbose_name='link'),
            preserve_default=False,
        ),
    ]
