# Generated by Django 5.1.1 on 2024-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jobpost_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='payment'),
            preserve_default=False,
        ),
    ]
